version: '3'

services:
  group1-specialist-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: group1-specialist-agent
    environment:
      - GROUP_NUMBER=1
      - FLASK_PORT=3001
    ports:
      - "3001:3001"
    volumes:
      - ./src/data:/app/src/data
      - ./src/config:/app/src/config

  group2-specialist-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: group2-specialist-agent
    environment:
      - GROUP_NUMBER=2
      - FLASK_PORT=3002
    ports:
      - "3002:3002"
    volumes:
      - ./src/data:/app/src/data
      - ./src/config:/app/src/config


  group3-specialist-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: group3-specialist-agent
    environment:
      - GROUP_NUMBER=3
      - FLASK_PORT=3003
    ports:
      - "3003:3003"
    volumes:
      - ./src/data:/app/src/data
      - ./src/config:/app/src/config


  group4-specialist-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: group4-specialist-agent
    environment:
      - GROUP_NUMBER=4
      - FLASK_PORT=3004
    ports:
      - "3004:3004"
    volumes:
      - ./src/data:/app/src/data
      - ./src/config:/app/src/config


  group5-specialist-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: group5-specialist-agent
    environment:
      - GROUP_NUMBER=5
      - FLASK_PORT=3005
    ports:
      - "3005:3005"
    volumes:
      - ./src/data:/app/src/data
      - ./src/config:/app/src/config
